name: CheckIn

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SITE_URL: ${{ secrets.SITE_URL }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Run Project
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python ./main.py
      - uses: gautamkrishnar/keepalive-workflow@master